# Generated by Django 2.1.4 on 2018-12-15 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='案件名')),
                ('text', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='概要')),
                ('created_date', models.DateField(default='', verbose_name='紹介日')),
                ('updated_date', models.DateField(blank=True, default='', null=True, verbose_name='更新日')),
                ('number', models.IntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='組合案件番号')),
                ('start_at', models.DateField(blank=True, default='', null=True, verbose_name='開始日')),
                ('end_at', models.DateField(blank=True, default='', null=True, verbose_name='終了日')),
                ('place', models.CharField(default='', max_length=50, verbose_name='場所')),
                ('member', models.IntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='人数')),
                ('first_skill', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='必須スキル')),
                ('second_skill', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='尚可スキル')),
                ('personal_skill', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='求める人物像')),
                ('lower_cost', models.IntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='下限単金')),
                ('upper_cost', models.IntegerField(blank=True, default='9999', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='上限単金')),
                ('comment', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='案件元企業')),
            ],
        ),
        migrations.CreateModel(
            name='LowSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_flag', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ロースキル案件')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(default='', max_length=20, verbose_name='国籍制限')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ステータス')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Category'),
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Company'),
        ),
        migrations.AddField(
            model_name='case',
            name='low_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.LowSkill'),
        ),
        migrations.AddField(
            model_name='case',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Nationality'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Status'),
        ),
    ]
