# Generated by Django 2.1.4 on 2018-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_date',
            field=models.DateField(default='', verbose_name='紹介日'),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_at',
            field=models.DateField(blank=True, default='', null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='case',
            name='first_skill',
            field=models.TextField(default='', max_length=100, verbose_name='必須スキル'),
        ),
        migrations.AlterField(
            model_name='case',
            name='personal_skill',
            field=models.TextField(default='', max_length=100, verbose_name='求める人物像'),
        ),
        migrations.AlterField(
            model_name='case',
            name='second_skill',
            field=models.TextField(default='', max_length=100, verbose_name='尚可スキル'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_at',
            field=models.DateField(blank=True, default='', null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='case',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='更新日'),
        ),
    ]
