# Generated by Django 2.1.4 on 2019-01-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20190108_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='low_skill',
        ),
        migrations.RemoveField(
            model_name='case',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
        migrations.DeleteModel(
            name='LowSkill',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
