# Generated by Django 2.1.4 on 2018-12-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20181214_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='first_skill',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='必須スキル'),
        ),
        migrations.AlterField(
            model_name='case',
            name='low_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.LowSkill'),
        ),
        migrations.AlterField(
            model_name='case',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Nationality'),
        ),
        migrations.AlterField(
            model_name='case',
            name='personal_skill',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='求める人物像'),
        ),
        migrations.AlterField(
            model_name='case',
            name='second_skill',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='尚可スキル'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Status'),
        ),
    ]
